### ISSUE TITLE
Blathers respond when @here or @everyone

### ISSUE THREAD

**Issue by ArtwoXYZ** [pnkllr/Blathers#3]
The bot respond when we try to @here or @everyone

![Image of at-here](https://i.imgur.com/JoNvHC1.png)

![Image of at-here](https://i.imgur.com/IP2fZA8.png)

**Comment by pnkllr** [comment]
This is working as intended. 

My only advice is, are you using the @everyone and @here tags in every channel or just onw channel like announcements etc?

If so, you can set up the channel so Blathers can see the channel (or not) but not able to send. This will prevent him from speaking in that channel were he was mentioned.

**Comment by nal532** [comment]
I made a pull request that should fix this if the maintainer is interested in changing how it works.

**Comment by pnkllr** [comment]
Fixed this in 586e394ef819886c10d3613a31e7948100d96b35 thanks to @Azurilex
